### ISSUE TITLE
ON dosnt work without arguments

### ISSUE THREAD

**Issue by Kainkun** [rgomezjnr/wizctrl#2]
OFF and SWITCH both work fine but I can't get ON to work without the --brightness arg

**Comment by rgomezjnr** [comment]
Hi Kainkun, I'm able to replicate the issue. I should have a fix for it soon. Thanks for the feedback!

**Comment by rgomezjnr** [comment]
I fixed the issue on the hotfix branch and tagged as version 0.2.2: [Fix ON command not working without arguments](https://github.com/rgomezjnr/wizcon/commit/7e46724d9e57acb3895795ec3f07b9331a233a1c). I uploaded version 0.2.2 to PyPI. You should be able to upgrade the package and confirm the issue is fixed:

`pip install wizcon --upgrade`

**Comment by Kainkun** [comment]
Its working now. Thanks!
